import { PDFDocument, PDFFont, PDFPage, StandardFonts, rgb } from 'pdf-lib';
import { PaymentView } from '../../core/models';
import { SchoolProfile } from '../../core/school.service';

export interface PaymentReceiptPdfOptions {
  french: boolean;
  payment: PaymentView;
  school: SchoolProfile | null;
}

const PAGE_WIDTH = 595;
const PAGE_HEIGHT = 842;
const MARGIN = 44;
const INK = rgb(0.06, 0.14, 0.24);
const BRAND = rgb(0.07, 0.29, 0.31);
const GOLD = rgb(0.82, 0.58, 0.14);
const MUTED = rgb(0.38, 0.44, 0.53);
const LINE = rgb(0.82, 0.86, 0.91);
const SOFT = rgb(0.96, 0.98, 0.98);

/** A clean, full-page A4 duplicate of a legacy finance payment receipt. */
export async function renderPaymentReceiptPdf(options: PaymentReceiptPdfOptions): Promise<Uint8Array> {
  const document = await PDFDocument.create();
  const normal = await document.embedFont(StandardFonts.Helvetica);
  const bold = await document.embedFont(StandardFonts.HelveticaBold);
  const page = document.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  const { payment, school, french } = options;

  document.setTitle(`${french ? 'Recu' : 'Receipt'} ${payment.receiptNo}`);
  document.setAuthor(school?.name || 'BBC SMS');

  page.drawRectangle({ x: 0, y: PAGE_HEIGHT - 12, width: PAGE_WIDTH, height: 12, color: BRAND });
  page.drawRectangle({ x: MARGIN, y: 735, width: 48, height: 48, color: INK });
  text(page, bold, 'BBC', MARGIN + 9, 752, 14, GOLD);
  text(page, bold, school?.name || 'Bayo Bilingual Complex', MARGIN + 62, 765, 17, INK);
  text(page, normal, contactLine(school), MARGIN + 62, 747, 8.5, MUTED);

  text(page, bold, french ? 'RECU DE PAIEMENT' : 'PAYMENT RECEIPT', MARGIN, 700, 11, BRAND);
  textRight(page, bold, payment.receiptNo, PAGE_WIDTH - MARGIN, 700, 11, INK);
  line(page, 685);

  label(page, bold, french ? 'ELEVE' : 'STUDENT', MARGIN, 648);
  text(page, bold, payment.studentName || (french ? 'Eleve supprime' : 'Deleted student'), MARGIN, 628, 15, INK);
  text(page, normal, [payment.matricule, payment.className].filter(Boolean).join('  |  ') || '-', MARGIN, 610, 9, MUTED);

  label(page, bold, french ? 'DATE DE PAIEMENT' : 'PAYMENT DATE', 370, 648);
  textRight(page, bold, payment.paidOn, PAGE_WIDTH - MARGIN, 627, 11, INK);
  if (school?.academicYear) textRight(page, normal, school.academicYear, PAGE_WIDTH - MARGIN, 610, 8.5, MUTED);

  page.drawRectangle({ x: MARGIN, y: 500, width: PAGE_WIDTH - (2 * MARGIN), height: 78, color: SOFT, borderColor: LINE, borderWidth: 1 });
  text(page, bold, french ? 'MONTANT RECU' : 'AMOUNT RECEIVED', MARGIN + 18, 548, 9, BRAND);
  textRight(page, bold, money(payment.amount), PAGE_WIDTH - MARGIN - 18, 526, 24, INK);

  detailRow(page, normal, bold, french ? 'Motif' : 'Purpose', payment.tranche
    ? `${french ? 'Frais scolaires - Tranche' : 'School fees - Installment'} ${payment.tranche}`
    : (french ? 'Frais scolaires' : 'School fees'), 454);
  detailRow(page, normal, bold, french ? 'Mode de paiement' : 'Payment method',
    (french ? payment.methodLabelFr : payment.methodLabelEn) || payment.method, 418);
  detailRow(page, normal, bold, french ? 'Compte credite' : 'Credited account', payment.treasuryAccountName || '-', 382);
  detailRow(page, normal, bold, french ? 'Reference' : 'Reference', payment.reference || '-', 346);

  page.drawRectangle({ x: MARGIN, y: 226, width: PAGE_WIDTH - (2 * MARGIN), height: 68, color: rgb(1, 1, 1), borderColor: LINE, borderWidth: 1 });
  text(page, bold, french ? 'PAIEMENT ENREGISTRE' : 'PAYMENT RECORDED', MARGIN + 18, 267, 9, rgb(0.08, 0.5, 0.28));
  text(page, normal, french
    ? 'Ce document confirme le versement indique ci-dessus.'
    : 'This document confirms the payment shown above.', MARGIN + 18, 246, 9, MUTED);

  line(page, 108);
  text(page, normal, french ? 'Recu genere electroniquement par BBC SMS.' : 'Electronically generated by BBC SMS.', MARGIN, 88, 8, MUTED);
  text(page, normal, french ? 'Conservez ce document pour vos archives.' : 'Keep this document for your records.', MARGIN, 75, 8, MUTED);
  textRight(page, bold, payment.receiptNo, PAGE_WIDTH - MARGIN, 82, 8, INK);
  page.drawRectangle({ x: 0, y: 0, width: PAGE_WIDTH, height: 10, color: BRAND });

  return document.save();
}

function detailRow(page: PDFPage, normal: PDFFont, bold: PDFFont, key: string, value: string, y: number): void {
  label(page, bold, key.toUpperCase(), MARGIN, y + 8);
  textRight(page, normal, value, PAGE_WIDTH - MARGIN, y + 8, 10, INK);
  page.drawLine({ start: { x: MARGIN, y }, end: { x: PAGE_WIDTH - MARGIN, y }, thickness: .6, color: LINE });
}

function label(page: PDFPage, font: PDFFont, value: string, x: number, y: number): void {
  text(page, font, value, x, y, 7.5, MUTED);
}

function line(page: PDFPage, y: number): void {
  page.drawLine({ start: { x: MARGIN, y }, end: { x: PAGE_WIDTH - MARGIN, y }, thickness: 1.2, color: BRAND });
}

function text(page: PDFPage, font: PDFFont, value: string, x: number, y: number, size: number, color: ReturnType<typeof rgb>): void {
  page.drawText(encodable(font, value), { x, y, size, font, color });
}

function textRight(page: PDFPage, font: PDFFont, value: string, right: number, y: number, size: number, color: ReturnType<typeof rgb>): void {
  const safe = encodable(font, value);
  page.drawText(safe, { x: right - font.widthOfTextAtSize(safe, size), y, size, font, color });
}

function money(value: number): string {
  return `${Math.round(value || 0).toLocaleString('fr-FR')} XAF`;
}

function contactLine(school: SchoolProfile | null): string {
  if (!school) return 'Maroua, Cameroon';
  return [[school.address, school.city, school.country].filter(Boolean).join(', '), school.phone, school.email]
    .filter(Boolean).join('  |  ');
}

function encodable(font: PDFFont, value: string): string {
  const source = String(value ?? '').replace(/\s+/g, ' ').trim();
  try { font.encodeText(source); return source; } catch {
    const folded = source.normalize('NFKD').replace(/[\u0300-\u036f]/g, '');
    const safe = folded.replace(/[^\x20-\x7E\xA0-\xFF]/g, '?');
    try { font.encodeText(safe); return safe; } catch { return safe.replace(/[^\x20-\x7E]/g, '?'); }
  }
}
