import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpErrorResponse } from '@angular/common/http';
import { TimetableApi, ClassRef, PeriodView, SlotView, SubjectTeacherView, TeacherSchedule } from './timetable.api';
import { SetupApi, SubjectView, TeacherOption } from '../../core/setup.api';
import { AuthService } from '../../core/auth.service';
import { I18nService } from '../../core/i18n.service';
import { CardComponent, EmptyComponent, PageHeaderComponent } from '../../core/ui';

type View='classes'|'teachers'|'periods';
interface Draft {dayIdx:number;slotIdx:number;subjectCode:string;teacherId:string;room:string;existing:boolean;}
const DAYS_FR=['Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'];
const DAYS_EN=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];

@Component({
 selector:'bbc-timetable',standalone:true,changeDetection:ChangeDetectionStrategy.OnPush,
 imports:[FormsModule,CardComponent,EmptyComponent,PageHeaderComponent],
 styles:[`
  .field{width:100%;min-height:42px;padding:.55rem .75rem;border:1px solid #cbd5e1;border-radius:.6rem;background:white;color:#172033;outline:none}.field:focus{border-color:#2563eb;box-shadow:0 0 0 3px rgba(37,99,235,.12)}.field.invalid{border-color:#e11d48;box-shadow:0 0 0 3px rgba(225,29,72,.1)}
  .label{display:block;font-size:.7rem;font-weight:700;text-transform:uppercase;letter-spacing:.05em;color:#64748b;margin-bottom:.35rem}.btn{min-height:38px;border-radius:.6rem;padding:.5rem .85rem;font-size:.8rem;font-weight:700;border:1px solid #cbd5e1;background:white;color:#334155}.btn:hover{background:#f8fafc}.btn.primary{background:#1d4ed8;border-color:#1d4ed8;color:white}.btn.danger{background:#be123c;border-color:#be123c;color:white}.btn:disabled{opacity:.45;cursor:not-allowed}
  .cell{min-height:90px;border:1px solid #e2e8f0;border-radius:.65rem;padding:.55rem;background:white;text-align:left}.cell.editable:hover{border-color:#60a5fa;background:#eff6ff}.cell.filled{border-color:#bfdbfe;background:#eff6ff}.cell.locked{cursor:default}
 `],
 template:`
 <div class="fade-in max-w-7xl mx-auto">
  <bbc-page-header [title]="i18n.t('timetable')" [subtitle]="fr()?'Planification par classe, contrôle des conflits et vues enseignants':'Class planning, conflict control and teacher views'" />
  <div class="flex gap-2 mb-5"><button class="btn" [class.primary]="view()==='classes'" (click)="view.set('classes')">{{fr()?'Planning des classes':'Class schedules'}}</button><button class="btn" [class.primary]="view()==='teachers'" (click)="view.set('teachers')">{{fr()?'Planning des enseignants':'Teacher schedules'}}</button>@if(auth.can('timetable','write')){<button class="btn" [class.primary]="view()==='periods'" (click)="view.set('periods')">{{fr()?'Périodes horaires':'Bell periods'}}</button>}</div>
  @if(notice()){<div class="mb-4 p-3 rounded-lg border text-sm font-medium" [class.bg-rose-50]="noticeType()==='error'" [class.border-rose-200]="noticeType()==='error'" [class.text-rose-800]="noticeType()==='error'" [class.bg-emerald-50]="noticeType()==='ok'" [class.border-emerald-200]="noticeType()==='ok'" [class.text-emerald-800]="noticeType()==='ok'">{{notice()}}</div>}

  @if(view()==='classes'){
   <bbc-card [title]="fr()?'1. Choisir et configurer une classe':'1. Select and configure a class'" [subtitle]="fr()?'Le modèle dépend du niveau: titulaire au primaire, enseignants par matière au secondaire.':'The model follows the level: homeroom in Primary, subject teachers in Secondary.'">
    <div class="grid md:grid-cols-3 gap-4">
     <label><span class="label">{{fr()?'Classe':'Class'}} <b class="text-rose-600">*</b></span><select class="field" [ngModel]="selectedClassId()" (ngModelChange)="selectClass($event)"><option value="">{{fr()?'Sélectionner une classe':'Select a class'}}</option>@for(c of classes();track c.id){<option [value]="c.id">{{c.name}} · {{modelLabel(c.model)}} · {{statusLabel(c.status)}}</option>}</select></label>
     @if(selectedClass();as c){<div><span class="label">{{fr()?'Modèle appliqué':'Applied model'}}</span><div class="field flex items-center font-semibold">{{modelLabel(c.model)}}</div></div><div><span class="label">{{fr()?'État':'Status'}}</span><div class="field flex items-center font-semibold" [class.text-emerald-700]="c.status==='PUBLISHED'">{{statusLabel(c.status)}}</div></div>}
    </div>
    @if(selectedClass();as c){
     <div class="mt-4 rounded-lg border p-3 text-sm" [class.bg-blue-50]="c.model==='HOMEROOM'" [class.border-blue-200]="c.model==='HOMEROOM'" [class.bg-violet-50]="c.model==='DEPARTMENTAL'" [class.border-violet-200]="c.model==='DEPARTMENTAL'">
      {{c.model==='HOMEROOM'?(fr()?'Règle: un seul titulaire assure toutes les matières de cette classe.':'Rule: one homeroom teacher handles every subject for this class.'):(fr()?'Règle: chaque matière utilise un enseignant qualifié et affecté à cette classe.':'Rule: every subject uses a qualified teacher assigned to this class.')}}
     </div>
     @if(c.model==='HOMEROOM'){
      <div class="grid md:grid-cols-[1fr_auto] gap-3 mt-4 items-end"><label><span class="label">{{fr()?'Enseignant titulaire':'Homeroom teacher'}} <b class="text-rose-600">*</b></span><select class="field" [(ngModel)]="homeroomTeacherId" [disabled]="c.status==='PUBLISHED'"><option value="">{{fr()?'Sélectionner le titulaire':'Select the homeroom teacher'}}</option>@for(t of teachers();track t.id){<option [value]="t.id">{{t.name}} ({{t.code}})</option>}</select></label><button class="btn primary" (click)="saveConfig()" [disabled]="c.status==='PUBLISHED'">{{fr()?'Enregistrer le titulaire':'Save homeroom teacher'}}</button></div>
     }@else{
       <div class="mt-4 rounded-lg border border-violet-200 bg-violet-50 p-4 text-sm"><div class="font-semibold text-violet-900">{{fr()?'Affectation des enseignants':'Teacher assignment'}}</div><div class="mt-1 text-violet-800">{{fr()?'Les enseignants sont gérés dans Paramètres → Configuration académique → Classes + matières. Le planning reprend automatiquement cette affectation.':'Manage teachers in Settings → Academic setup → Class subjects. The timetable inherits that assignment automatically.'}}</div></div>
     }
     <div class="flex gap-2 mt-4">@if(c.status==='DRAFT'){<button class="btn primary" (click)="openPublish()" [disabled]="slots().length===0">{{fr()?'Publier et verrouiller':'Publish and lock'}}</button>}@else{<button class="btn" (click)="openReopen()">{{fr()?'Rouvrir avec motif':'Reopen with reason'}}</button>}<button class="btn" onclick="window.print()">{{fr()?'Imprimer':'Print'}}</button></div>
    }
   </bbc-card>

   @if(selectedClass();as c){
    <div class="mt-5"><bbc-card [title]="fr()?'2. Construire la grille hebdomadaire':'2. Build the weekly grid'" [subtitle]="c.status==='PUBLISHED'?(fr()?'Planning publié: il alimente les appels secondaires et ne peut plus être modifié.':'Published schedule: it feeds Secondary attendance and is locked.'):(fr()?'Cliquez sur une case. Les conflits d’enseignant et de salle sont strictement refusés.':'Click a cell. Teacher and room conflicts are strictly blocked.')">
     <div class="overflow-x-auto"><div class="min-w-[1100px] grid gap-2" [style.grid-template-columns]="gridColumns()">
      <div></div>@for(p of periods();track p.id){<div class="text-center text-xs font-bold text-slate-600 p-2">{{p.label}}<div class="font-normal">{{p.startTime}}–{{p.endTime}}</div></div>}
      @for(day of dayIdxs;track day){<div class="font-bold text-sm p-2">{{dayName(day)}}</div>@for(p of periods();track p.id){@if(slotAt(day,p.slotIdx);as s){<button class="cell filled" [class.editable]="c.status==='DRAFT'" [class.locked]="c.status==='PUBLISHED'" (click)="edit(day,p.slotIdx)"><b>{{subjectName(s.subjectCode)}}</b><div class="text-xs mt-1">{{teacherName(s.teacherId)}}</div><div class="text-xs text-slate-500">{{s.room||'—'}}</div></button>}@else{<button class="cell" [class.editable]="c.status==='DRAFT'" [disabled]="c.status==='PUBLISHED'" (click)="edit(day,p.slotIdx)"><span class="text-slate-400 text-xs">{{fr()?'+ Ajouter':'+ Add'}}</span></button>}}}
     </div></div>
    </bbc-card></div>
   }@else{<div class="mt-5"><bbc-card><bbc-empty icon="calendar" [label]="fr()?'Sélectionnez une classe pour commencer.':'Select a class to begin.'"/></bbc-card></div>}
  }@else if(view()==='teachers'){
   <bbc-card [title]="fr()?'Planning personnalisé d’un enseignant':'Personalized teacher schedule'" [subtitle]="fr()?'Seuls les plannings publiés apparaissent ici.':'Only published class schedules appear here.'">
    <div class="grid md:grid-cols-[1fr_auto] gap-3 items-end"><label><span class="label">{{fr()?'Enseignant':'Teacher'}} <b class="text-rose-600">*</b></span><select class="field" [(ngModel)]="selectedTeacherId" (ngModelChange)="loadTeacherSchedule($event)"><option value="">{{fr()?'Sélectionner un enseignant':'Select a teacher'}}</option>@for(t of allTeachers();track t.id){<option [value]="t.id">{{t.name}} ({{t.code}})</option>}</select></label><button class="btn" onclick="window.print()">{{fr()?'Imprimer':'Print'}}</button></div>
    @if(teacherSchedule();as schedule){<div class="mt-4"><div class="font-bold text-lg">{{schedule.teacherName}}</div><div class="text-sm text-slate-500 mb-4">{{schedule.sessionLabel}}</div><div class="overflow-x-auto"><div class="min-w-[1100px] grid gap-2" [style.grid-template-columns]="gridColumns()"><div></div>@for(p of periods();track p.id){<div class="text-center text-xs font-bold p-2">{{p.label}}<div class="font-normal">{{p.startTime}}</div></div>}@for(day of dayIdxs;track day){<div class="font-bold text-sm p-2">{{dayName(day)}}</div>@for(p of periods();track p.id){@if(teacherSlotAt(day,p.slotIdx);as s){<div class="cell filled"><b>{{s.className}}</b><div class="text-xs">{{subjectName(s.subjectCode)}}</div><div class="text-xs text-slate-500">{{s.room||'—'}}</div></div>}@else{<div class="cell bg-slate-50"></div>}}}</div></div></div>}@else if(selectedTeacherId){<bbc-empty icon="calendar" [label]="fr()?'Aucun cours publié pour cet enseignant.':'No published course for this teacher.'"/>}
   </bbc-card>
  }@else{
   <bbc-card [title]="fr()?'Configuration des périodes horaires':'Bell-period configuration'" [subtitle]="fr()?'Ces heures ne sont pas codées en dur: elles pilotent la grille de toutes les classes. Les chevauchements sont refusés.':'These times are not hardcoded: they drive every class grid. Overlaps are rejected.'">
    <div class="space-y-3">@for(p of periods();track p.id){<div class="grid md:grid-cols-[90px_1fr_1fr_1fr_auto] gap-3 items-end border border-slate-200 rounded-lg p-3"><div class="font-bold text-slate-700">P{{p.slotIdx+1}}</div><label><span class="label">{{fr()?'Libellé':'Label'}}</span><input class="field" [(ngModel)]="p.label"></label><label><span class="label">{{fr()?'Début':'Start'}}</span><input class="field" type="time" [(ngModel)]="p.startTime"></label><label><span class="label">{{fr()?'Fin':'End'}}</span><input class="field" type="time" [(ngModel)]="p.endTime"></label><button class="btn primary" (click)="savePeriod(p)">{{fr()?'Enregistrer':'Save'}}</button></div>}</div>
   </bbc-card>
  }
 </div>

 @if(draft();as d){<div class="fixed inset-0 z-50 bg-slate-950/45 flex items-center justify-center p-4" (click)="cancelEdit()"><div class="bg-white rounded-xl shadow-2xl max-w-lg w-full p-5" (click)="$event.stopPropagation()"><h3 class="text-lg font-bold">{{dayName(d.dayIdx)}} · {{periodLabel(d.slotIdx)}}</h3><p class="text-sm text-slate-500 mt-1">{{fr()?'Tous les champs marqués sont obligatoires.':'All marked fields are required.'}}</p><div class="grid gap-4 mt-4"><label><span class="label">{{fr()?'Matière':'Subject'}} <b class="text-rose-600">*</b></span><select class="field" [class.invalid]="attempted()&&!d.subjectCode" [ngModel]="d.subjectCode" (ngModelChange)="setDraftSubject($event)"><option value="">{{fr()?'Sélectionner une matière':'Select a subject'}}</option>@for(s of subjectsForClass();track s.id){<option [value]="s.code">{{subjectLabel(s)}} ({{s.code}})</option>}</select>@if(attempted()&&!d.subjectCode){<div class="text-xs text-rose-600 mt-1">{{fr()?'La matière est obligatoire.':'Subject is required.'}}</div>}</label><label><span class="label">{{fr()?'Enseignant':'Teacher'}} <b class="text-rose-600">*</b></span><select class="field bg-slate-50" [class.invalid]="attempted()&&!d.teacherId" [ngModel]="d.teacherId" disabled><option value="">{{fr()?'Aucun enseignant responsable':'No responsible teacher assigned'}}</option>@if(d.teacherId){<option [value]="d.teacherId">{{assignedTeacherName(d.subjectCode,d.teacherId)}}</option>}</select><div class="text-xs text-slate-500 mt-1">@if(subjectTeacher(d.subjectCode);as mapping){@if(mapping.teacherId){ {{fr()?'Automatique depuis la configuration classe + matière.':'Automatically inherited from the class + subject assignment.'}} } @else { {{mapping.message}} }} @else { {{fr()?'Chargement de l’affectation...':'Loading the class-subject assignment...'}} }</div>@if(attempted()&&!d.teacherId){<div class="text-xs text-rose-600 mt-1">{{fr()?'L’enseignant est obligatoire.':'Teacher is required.'}}</div>}</label><label><span class="label">{{fr()?'Salle':'Room'}}</span><input class="field" [(ngModel)]="d.room" list="rooms" placeholder="S1, Lab…"><datalist id="rooms">@for(r of rooms();track r){<option [value]="r"></option>}</datalist></label></div><div class="flex gap-2 mt-5">@if(d.existing){<button class="btn danger" (click)="remove()">{{fr()?'Supprimer':'Delete'}}</button>}<div class="flex-1"></div><button class="btn" (click)="cancelEdit()">{{fr()?'Annuler':'Cancel'}}</button><button class="btn primary" (click)="saveSlot()">{{fr()?'Enregistrer':'Save'}}</button></div></div></div>}
 @if(modal()){<div class="fixed inset-0 z-50 bg-slate-950/45 flex items-center justify-center p-4" (click)="closeModal()"><div class="bg-white rounded-xl shadow-2xl max-w-md w-full p-5" (click)="$event.stopPropagation()"><h3 class="text-lg font-bold">{{modal()==='publish'?(fr()?'Publier ce planning ?':'Publish this schedule?'):(fr()?'Rouvrir le planning ?':'Reopen the schedule?')}}</h3><p class="text-sm text-slate-600 mt-2">{{modal()==='publish'?(fr()?'Le planning sera verrouillé et alimentera les appels par période.':'The schedule will be locked and will feed period attendance.'):(fr()?'Les appels futurs suivront la prochaine version publiée. Le motif est conservé.':'Future attendance will follow the next published version. The reason is retained.')}}</p>@if(modal()==='reopen'){<label class="block mt-4"><span class="label">{{fr()?'Motif':'Reason'}} <b class="text-rose-600">*</b></span><textarea class="field min-h-24" [class.invalid]="modalAttempted()&&!reopenReason.trim()" [(ngModel)]="reopenReason"></textarea>@if(modalAttempted()&&!reopenReason.trim()){<div class="text-xs text-rose-600 mt-1">{{fr()?'Le motif est obligatoire.':'Reason is required.'}}</div>}</label>}<div class="flex justify-end gap-2 mt-5"><button class="btn" (click)="closeModal()">{{fr()?'Annuler':'Cancel'}}</button><button class="btn primary" (click)="confirmModal()">{{modal()==='publish'?(fr()?'Publier':'Publish'):(fr()?'Rouvrir':'Reopen')}}</button></div></div></div>}
 `
})
export class TimetableComponent {
 protected i18n=inject(I18nService); private api=inject(TimetableApi); private setup=inject(SetupApi); protected auth=inject(AuthService);
 protected fr=()=>this.i18n.lang()==='fr'; protected view=signal<View>('classes'); protected classes=signal<ClassRef[]>([]); protected periods=signal<PeriodView[]>([]); protected slots=signal<SlotView[]>([]); protected subjects=signal<SubjectView[]>([]); protected teachers=signal<TeacherOption[]>([]); protected allTeachers=signal<TeacherOption[]>([]); protected rooms=signal<string[]>([]);
 protected selectedClassId=signal(''); protected homeroomTeacherId=''; protected assignmentTeacherId=''; protected assignmentSubjects=signal<Set<string>>(new Set()); protected subjectTeachers=signal<SubjectTeacherView[]|null>(null); protected selectedTeacherId=''; protected teacherSchedule=signal<TeacherSchedule|null>(null); protected draft=signal<Draft|null>(null); protected attempted=signal(false); protected notice=signal(''); protected noticeType=signal<'ok'|'error'>('ok'); protected modal=signal<'publish'|'reopen'|null>(null); protected reopenReason=''; protected modalAttempted=signal(false); protected dayIdxs=[0,1,2,3,4,5];
 protected selectedClass=computed(()=>this.classes().find(c=>c.id===this.selectedClassId())||null);
 protected subjectsForClass=computed(()=>{const c=this.selectedClass(),mappings=this.subjectTeachers();const candidates=this.subjects().filter(s=>!c?.subsystem||!s.subsystem||s.subsystem===c.subsystem);if(mappings===null)return candidates;const codes=new Set(mappings.map(m=>m.subjectCode));return candidates.filter(s=>codes.has(s.code));});
 constructor(){this.loadClasses();this.api.periods().subscribe(v=>this.periods.set(v));this.api.rooms().subscribe(v=>this.rooms.set(v));this.setup.listSubjects().subscribe(v=>this.subjects.set(v));this.setup.assignableTeachers().subscribe(v=>this.allTeachers.set(v));}
 private loadClasses(selectId?:string){this.api.classes().subscribe(v=>{this.classes.set(v);if(selectId){this.selectedClassId.set(selectId);const c=this.selectedClass();this.homeroomTeacherId=c?.homeroomTeacherId||'';}});}
 protected selectClass(id:string){this.selectedClassId.set(id);this.slots.set([]);this.subjectTeachers.set(null);this.draft.set(null);const c=this.selectedClass();this.homeroomTeacherId=c?.homeroomTeacherId||'';if(c){this.setup.assignableTeachers(c.level).subscribe(v=>this.teachers.set(v));this.loadSubjectTeachers(c.id);this.api.grid(c.name).subscribe(v=>this.slots.set(v));}}
 protected saveConfig(){const c=this.selectedClass();if(!c)return;if(c.model==='HOMEROOM'&&!this.homeroomTeacherId){this.error(this.fr()?'Sélectionnez l’enseignant titulaire.':'Select the homeroom teacher.');return;}this.api.configure(c.id,this.homeroomTeacherId||null,c.version).subscribe({next:v=>{this.replaceClass(v);this.loadSubjectTeachers(c.id);this.ok(this.fr()?'Titulaire enregistré.':'Homeroom teacher saved.');},error:e=>this.fail(e)});}
 protected subjectTeacher(code:string|null):SubjectTeacherView|null{return code?this.subjectTeachers()?.find(m=>m.subjectCode===code)||null:null;}
 protected assignedTeacherName(code:string,teacherId:string):string{const mapping=this.subjectTeacher(code);return mapping?.teacherName||this.teacherName(teacherId);}
 private loadSubjectTeachers(classId:string){this.api.subjectTeachers(classId).subscribe({next:v=>this.subjectTeachers.set(v),error:e=>{this.subjectTeachers.set([]);this.fail(e);}});}
 protected setDraftSubject(code:string){const mapping=this.subjectTeacher(code);this.draft.update(current=>current?{...current,subjectCode:code,teacherId:mapping?.teacherId||''}:current);}
 protected toggleAssignmentSubject(code:string,checked:boolean){this.assignmentSubjects.update(current=>{const next=new Set(current);checked?next.add(code):next.delete(code);return next;});}
 protected assignTeacher(){const c=this.selectedClass(),subjects=[...this.assignmentSubjects()];if(!c||!this.assignmentTeacherId||subjects.length===0){this.error(this.fr()?'Sélectionnez un enseignant et au moins une matière.':'Select a teacher and at least one subject.');return;}this.api.assignTeacher(c.id,this.assignmentTeacherId,subjects).subscribe({next:()=>{this.assignmentSubjects.set(new Set());this.ok(this.fr()?'Enseignant affecté à la classe et aux matières sélectionnées.':'Teacher assigned to the class and selected subjects.');},error:e=>this.fail(e)});}
 protected edit(dayIdx:number,slotIdx:number){const c=this.selectedClass();if(!c||c.status==='PUBLISHED')return;const s=this.slotAt(dayIdx,slotIdx),mapped=s?.subjectCode?this.subjectTeacher(s.subjectCode):null;this.attempted.set(false);this.draft.set({dayIdx,slotIdx,subjectCode:s?.subjectCode||'',teacherId:mapped?.teacherId||s?.teacherId||(c.model==='HOMEROOM'?c.homeroomTeacherId||'':''),room:s?.room||'',existing:!!s});}
 protected saveSlot(){const d=this.draft(),c=this.selectedClass();if(!d||!c)return;this.attempted.set(true);if(!d.subjectCode){this.error(this.fr()?'La matière est obligatoire.':'Subject is required.');return;}if(!d.teacherId){const mapping=this.subjectTeacher(d.subjectCode);this.error(mapping?.message||(this.fr()?'Aucun enseignant responsable n’est affecté.':'No responsible teacher is assigned.'));return;}this.api.saveSlot({className:c.name,dayIdx:d.dayIdx,slotIdx:d.slotIdx,subjectCode:d.subjectCode,teacherId:d.teacherId,room:d.room||undefined}).subscribe({next:()=>{this.draft.set(null);this.selectClass(c.id);this.loadClasses(c.id);this.ok(this.fr()?'Cours enregistré.':'Course saved.');},error:e=>this.fail(e)});}
 protected remove(){const d=this.draft(),c=this.selectedClass();if(!d||!c)return;this.api.deleteSlot(c.name,d.dayIdx,d.slotIdx).subscribe({next:()=>{this.draft.set(null);this.selectClass(c.id);this.loadClasses(c.id);this.ok(this.fr()?'Cours supprimé.':'Course deleted.');},error:e=>this.fail(e)});}
 protected cancelEdit(){this.draft.set(null);}
 protected openPublish(){this.modal.set('publish');this.modalAttempted.set(false);} protected openReopen(){this.modal.set('reopen');this.modalAttempted.set(false);this.reopenReason='';} protected closeModal(){this.modal.set(null);}
 protected confirmModal(){const c=this.selectedClass();if(!c)return;if(this.modal()==='reopen'){this.modalAttempted.set(true);if(!this.reopenReason.trim())return;this.api.reopen(c.id,c.version,this.reopenReason).subscribe({next:v=>{this.replaceClass(v);this.closeModal();this.ok(this.fr()?'Planning rouvert.':'Schedule reopened.');},error:e=>this.fail(e)});}else{this.api.publish(c.id,c.version).subscribe({next:v=>{this.replaceClass(v);this.closeModal();this.ok(this.fr()?'Planning publié et disponible pour les appels.':'Schedule published and available to attendance.');},error:e=>this.fail(e)});}}
 protected loadTeacherSchedule(id:string){this.teacherSchedule.set(null);if(id)this.api.teacherSchedule(id).subscribe({next:v=>this.teacherSchedule.set(v),error:e=>this.fail(e)});}
 protected savePeriod(p:PeriodView){this.api.updatePeriod(p).subscribe({next:v=>{this.periods.update(all=>all.map(x=>x.slotIdx===v.slotIdx?v:x));this.ok(this.fr()?'Période enregistrée.':'Period saved.');},error:e=>this.fail(e)});}
 protected slotAt(d:number,p:number){return this.slots().find(s=>s.dayIdx===d&&s.slotIdx===p);} protected teacherSlotAt(d:number,p:number){return this.teacherSchedule()?.slots.find(s=>s.dayIdx===d&&s.slotIdx===p);} protected gridColumns(){return `90px repeat(${Math.max(1,this.periods().length)},minmax(120px,1fr))`;}
 protected dayName(i:number){return (this.fr()?DAYS_FR:DAYS_EN)[i]||'';} protected periodLabel(i:number){const p=this.periods().find(x=>x.slotIdx===i);return p?`${p.label} · ${p.startTime}–${p.endTime}`:`P${i+1}`;} protected modelLabel(m:string){return m==='HOMEROOM'?(this.fr()?'Titulaire (appel quotidien)':'Homeroom (daily roll)'):(this.fr()?'Départemental (appel par période)':'Departmental (period roll)');} protected statusLabel(s:string){return s==='PUBLISHED'?(this.fr()?'Publié':'Published'):(this.fr()?'Brouillon':'Draft');}
 protected subjectLabel(s:SubjectView){return (this.fr()?s.label?.['fr']:s.label?.['en'])||s.label?.['fr']||s.code;} protected subjectName(code:string|null){const s=this.subjects().find(x=>x.code===code);return s?this.subjectLabel(s):(code||'—');} protected teacherName(id:string|null){return this.allTeachers().find(t=>t.id===id)?.name||this.teachers().find(t=>t.id===id)?.name||'—';}
 private replaceClass(v:ClassRef){this.classes.update(all=>all.map(c=>c.id===v.id?v:c));this.homeroomTeacherId=v.homeroomTeacherId||'';}
 private fail(e:HttpErrorResponse|any){this.error(e?.error?.message||e?.error?.detail||e?.message||(this.fr()?'Une erreur est survenue.':'An error occurred.'));} private ok(m:string){this.noticeType.set('ok');this.notice.set(m);} private error(m:string){this.noticeType.set('error');this.notice.set(m);}
}
