import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { downloadCsv } from '../../core/csv';
import { ClassView, SetupApi } from '../../core/setup.api';
import { I18nService } from '../../core/i18n.service';
import { CardComponent, IconComponent, PageHeaderComponent } from '../../core/ui';
import { FamilyImportRow, FamilyImportView, StudentApi } from './students.api';

interface LegacyHeaderMap { externalKey?:number; lastName?:number; firstName?:number; sex?:number; dob?:number; birthplace?:number; niu?:number; repeats?:number; fatherName?:number; fatherPhone?:number; fatherEmail?:number; motherName?:number; motherPhone?:number; motherEmail?:number; guardianName?:number; guardianRelation?:number; guardianPhone?:number; guardianEmail?:number; }

@Component({selector:'bbc-family-import',standalone:true,changeDetection:ChangeDetectionStrategy.OnPush,imports:[FormsModule,RouterLink,CardComponent,IconComponent,PageHeaderComponent],template:`
<div class="fade-in max-w-5xl mx-auto space-y-5"><bbc-page-header [title]="fr()?'Import familial sécurisé':'Secure family import'" [subtitle]="fr()?'Conserver le modèle élèves, relier toute la famille':'Keep the student template, link the whole family'"><a right routerLink="/students" class="btn-secondary"><bbc-icon name="chevronLeft" [s]="14"/> {{fr()?'Retour':'Back'}}</a></bbc-page-header><bbc-card>
<div class="mb-5 rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900"><b>{{fr()?'Format conservé':'Format preserved'}}</b><p class="mt-1">{{fr()?'Utilisez le modèle élèves historique à 17 colonnes. Les colonnes père, mère et tuteur deviennent automatiquement plusieurs relations familiales avec leur lien.':'Use the original 17-column student template. Father, mother and guardian columns automatically become separate family relationships with their relation.'}}</p></div>
<div class="grid md:grid-cols-3 gap-4 mb-5"><label><span class="label">{{fr()?'Classe cible':'Target class'}}<span class="required-mark">*</span><span class="required-hint">{{fr()?'Obligatoire':'Required'}}</span></span><select class="input w-full" [(ngModel)]="classId" [class.input-error]="attempted()&&!classId"><option value="">{{fr()?'Sélectionner une classe':'Select a class'}}</option>@for(c of classes();track c.id){<option [value]="c.id">{{c.name}}</option>}</select>@if(attempted()&&!classId){<span class="field-error">{{fr()?'Sélectionnez la classe cible.':'Select the target class.'}}</span>}</label><label><span class="label">{{fr()?'Relation par défaut pour les tuteurs':'Default relationship for guardians'}}<span class="required-mark">*</span></span><input class="input w-full" [(ngModel)]="relationship" [class.input-error]="attempted()&&!relationship.trim()"/>@if(attempted()&&!relationship.trim()){<span class="field-error">{{fr()?'La relation par défaut est obligatoire.':'Default relationship is required.'}}</span>}</label><label><span class="label">{{fr()?'Mode d’accès':'Access mode'}}</span><select class="input w-full" [(ngModel)]="accessMode"><option value="SEND_INVITE">{{fr()?'Invitation si un e-mail existe':'Invite when email exists'}}</option><option value="NO_PORTAL">{{fr()?'Sans portail':'No portal'}}</option></select></label></div>
<div class="p-4 rounded-xl border border-dashed bg-slate-50 mb-4"><div class="flex flex-wrap gap-2 items-center"><label class="btn-secondary cursor-pointer"><bbc-icon name="upload" [s]="14"/> {{fr()?'Choisir CSV / Excel':'Choose CSV / Excel'}}<input class="hidden" type="file" accept=".csv,.xlsx,.xls,.xlsm" (change)="onFile($event)"/></label><button class="btn-secondary" type="button" (click)="downloadTemplate()">{{fr()?'Télécharger le modèle élèves':'Download student template'}}</button>@if(fileName()){<span class="text-sm text-mute">{{fileName()}}</span>}</div><p class="text-xs text-mute mt-2">nom, prenom, sexe, date_naissance, lieu_naissance, niu, redouble, pere_*, mere_*, tuteur_*</p></div>
<label class="label">{{fr()?'Aperçu modifiable':'Editable preview'}}<span class="required-mark">*</span></label><textarea class="input w-full font-mono" rows="10" [(ngModel)]="text" [class.input-error]="attempted()&&!text.trim()" placeholder="nom,prenom,sexe,date_naissance,lieu_naissance,niu,redouble,pere_nom,..."></textarea>@if(attempted()&&!text.trim()){<span class="field-error">{{fr()?'Ajoutez au moins une ligne ou sélectionnez un fichier.':'Add at least one row or choose a file.'}}</span>}@if(attempted()&&!importValid()){<div role="alert" class="mt-4 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm font-semibold text-rose-700">{{fr()?'Corrigez les champs en rouge avant de prévisualiser.':'Correct the fields in red before previewing.'}}</div>}<div class="flex justify-end mt-4"><button class="btn-primary" [disabled]="working()" (click)="dryRun()">{{fr()?'Prévisualiser l’import':'Preview import'}}</button></div>
@if(result();as r){<div class="mt-6 space-y-3"><div class="grid grid-cols-4 gap-3"><div class="stat"><b>{{r.totalRows}}</b><span>Total</span></div><div class="stat"><b>{{r.validRows}}</b><span>{{fr()?'Valides':'Valid'}}</span></div><div class="stat"><b>{{r.createdRows}}</b><span>{{fr()?'Créés':'Created'}}</span></div><div class="stat"><b>{{r.failedRows}}</b><span>{{fr()?'Erreurs':'Errors'}}</span></div></div><div class="border rounded-xl overflow-hidden">@for(row of r.rows;track row.externalKey){<div class="grid grid-cols-[4rem_1fr_7rem_2fr] gap-2 p-2 border-t text-xs"><span>#{{row.rowNumber}}</span><b>{{row.studentName}}</b><span>{{row.outcome}}</span><span>{{row.message}}</span></div>}</div><div class="flex justify-between gap-2"><button class="btn-secondary" type="button" (click)="downloadResults()">{{fr()?'Télécharger le rapport':'Download report'}}</button>@if(r.status==='VALIDATED'){<button class="btn-primary" [disabled]="working()" (click)="commit()">{{fr()?'Valider l’import':'Commit import'}}</button>}</div>@if(r.status==='VALIDATED'){<div class="p-3 rounded-xl bg-blue-50 text-blue-800 text-sm">{{fr()?'La prévisualisation n’a créé aucun élève. Seules les lignes valides seront exécutées.':'Preview created no students. Only valid rows will be executed.'}}</div>}@else{<div class="p-3 rounded-xl bg-emerald-50 text-emerald-800">{{fr()?'Import terminé. Une relance ne dupliquera pas les lignes déjà validées.':'Import completed. Retrying will not duplicate committed rows.'}}</div>}</div>}
@if(error()){<div role="alert" class="mt-3 p-3 border border-rose-200 bg-rose-50 text-rose-700 rounded-xl">{{error()}}</div>}</bbc-card></div>`,styles:[`.stat{display:flex;flex-direction:column;padding:.75rem;background:#f8fafc;border-radius:.75rem}.stat b{font-size:1.25rem}.stat span{font-size:.7rem;color:#64748b}`]})
export class FamilyImportComponent {
  private api=inject(StudentApi); private setup=inject(SetupApi); private i18n=inject(I18nService);
  protected fr=()=>this.i18n.lang()==='fr'; protected classes=signal<ClassView[]>([]); protected result=signal<FamilyImportView|null>(null); protected working=signal(false); protected error=signal<string|null>(null); protected attempted=signal(false); protected fileName=signal('');
  protected classId=''; protected relationship='GUARDIAN'; protected accessMode='SEND_INVITE'; protected text='';
  private readonly legacyHeaders=['nom','prenom','sexe','date_naissance','lieu_naissance','niu','redouble','pere_nom','pere_telephone','pere_email','mere_nom','mere_telephone','mere_email','tuteur_nom','tuteur_lien','tuteur_telephone','tuteur_email'];
  constructor(){this.setup.listClasses().subscribe(c=>this.classes.set(c));}

  protected async onFile(event:Event):Promise<void>{const input=event.target as HTMLInputElement;const file=input.files?.[0];if(!file)return;this.error.set(null);this.result.set(null);try{const XLSX=await import('xlsx');const workbook=XLSX.read(await file.arrayBuffer(),{type:'array'});const sheet=workbook.Sheets[workbook.SheetNames[0]];if(!sheet)throw new Error('empty');this.text=XLSX.utils.sheet_to_csv(sheet,{FS:';',RS:'\n'});this.fileName.set(file.name);}catch{this.error.set(this.fr()?'Fichier illisible. Utilisez le modèle CSV ou Excel.':'Unreadable file. Use the CSV or Excel template.');}finally{input.value='';}}
  protected downloadTemplate():void{downloadCsv('modele-eleves.csv',this.legacyHeaders,[['DUPONT','Jean','M','2015-03-12','Douala','','non','DUPONT Paul','+237 6XX XX XX XX','paul.dupont@example.cm','NGO Marie','+237 6XX XX XX XX','marie.ngo@example.cm','','','','']]);}
  protected downloadResults():void{const result=this.result();if(!result)return;const safe=(value:string)=>/^[=+\-@]/.test(value)?`'${value}`:value;downloadCsv(`rapport-import-familles-${result.jobId}.csv`,['row','external_key','student','outcome','message'],result.rows.map(row=>[row.rowNumber,safe(row.externalKey),safe(row.studentName),row.outcome,safe(row.message)]));}

  private rows():FamilyImportRow[]{const lines=this.text.split(/\r?\n/).map(line=>line.trim()).filter(Boolean);if(!lines.length)return[];const delimiter=this.detectDelimiter(lines[0]);const records=lines.map(line=>this.splitLine(line,delimiter));const header=this.headerMap(records[0]);const data=header?records.slice(1):records;const idx=header||{lastName:0,firstName:1,sex:2,dob:3,birthplace:4,niu:5,repeats:6,fatherName:7,fatherPhone:8,fatherEmail:9,motherName:10,motherPhone:11,motherEmail:12,guardianName:13,guardianRelation:14,guardianPhone:15,guardianEmail:16,externalKey:-1};const value=(row:string[],key:string)=>{const position=(idx as Record<string,number>)[key];return position===undefined||position<0?'':(row[position]??'').trim();};return data.map((row,rowNumber)=>{const lastName=value(row,'lastName'),firstName=value(row,'firstName'),dob=this.normalizeDate(value(row,'dob'));const externalKey=value(row,'externalKey')||`legacy:${value(row,'niu')||`${lastName}|${firstName}|${dob||rowNumber}`}`;const guardians=[this.guardian(value(row,'fatherName'),value(row,'fatherPhone'),value(row,'fatherEmail'),'FATHER'),this.guardian(value(row,'motherName'),value(row,'motherPhone'),value(row,'motherEmail'),'MOTHER'),this.guardian(value(row,'guardianName'),value(row,'guardianPhone'),value(row,'guardianEmail'),value(row,'guardianRelation')||this.relationship)].filter((guardian):guardian is NonNullable<typeof guardian>=>!!guardian);return{externalKey,firstName,lastName,niu:value(row,'niu')||null,sex:this.normalizeSex(value(row,'sex')),dob,birthplace:value(row,'birthplace')||null,repeats:this.normalizeYesNo(value(row,'repeats')),classId:this.classId,guardians};});}
  private guardian(displayName:string,phone:string,email:string,relationshipType:string){if(!displayName)return null;return{displayName,phone:phone||null,email:email||null,relationshipType,accessMode:email?this.accessMode:'NO_PORTAL'};}
  private detectDelimiter(line:string):string{const counts={',':(line.match(/,/g)||[]).length,';':(line.match(/;/g)||[]).length,'\t':(line.match(/\t/g)||[]).length};return Object.entries(counts).sort((a,b)=>b[1]-a[1])[0][0];}
  private splitLine(line:string,delimiter:string):string[]{const result:string[]=[];let cell='';let quoted=false;for(let i=0;i<line.length;i++){const char=line[i];if(char==='"'&&line[i+1]==='"'){cell+='"';i++;continue;}if(char==='"'){quoted=!quoted;continue;}if(char===delimiter&&!quoted){result.push(cell.trim());cell='';continue;}cell+=char;}result.push(cell.trim());return result;}
  private normalizeHeader(value:string):string{return value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');}
  private headerMap(row:string[]):LegacyHeaderMap|null{const map:LegacyHeaderMap={};row.forEach((cell,index)=>{const key=this.normalizeHeader(cell);if(key.includes('externalkey'))map.externalKey=index;else if(key==='nom'||key==='lastname'||key==='surname')map.lastName=index;else if(key==='prenom'||key==='firstname')map.firstName=index;else if(key.includes('sexe')||key==='sex')map.sex=index;else if(key.includes('date')||key==='dob')map.dob=index;else if(key.includes('lieu')||key.includes('birthplace'))map.birthplace=index;else if(key==='niu'||key.includes('identifiant'))map.niu=index;else if(key.includes('redouble')||key.includes('repeat'))map.repeats=index;else if(key.includes('perenom')||key.includes('fathername'))map.fatherName=index;else if(key.includes('pere')&&(key.includes('tel')||key.includes('phone')))map.fatherPhone=index;else if(key.includes('pere')&&(key.includes('email')||key.includes('mail')))map.fatherEmail=index;else if(key.includes('merenom')||key.includes('mothername'))map.motherName=index;else if(key.includes('mere')&&(key.includes('tel')||key.includes('phone')))map.motherPhone=index;else if(key.includes('mere')&&(key.includes('email')||key.includes('mail')))map.motherEmail=index;else if(key.includes('tuteurnom')||key.includes('guardianname'))map.guardianName=index;else if(key.includes('tuteur')&&(key.includes('lien')||key.includes('relation')))map.guardianRelation=index;else if(key.includes('tuteur')&&(key.includes('tel')||key.includes('phone')))map.guardianPhone=index;else if(key.includes('tuteur')&&(key.includes('email')||key.includes('mail')))map.guardianEmail=index;});return map.lastName===undefined&&map.firstName===undefined?null:map;}
  private normalizeSex(value:string):string{return/^(m|masculin|male)/i.test(value)?'M':/^(f|feminin|female|fille)/i.test(value)?'F':'';}
  private normalizeYesNo(value:string):boolean{return/^(o|oui|y|yes|1|true|vrai)/i.test(value);}
  private normalizeDate(value:string):string|null{if(!value)return null;const iso=value.match(/^(\d{4})[-/](\d{1,2})[-/](\d{1,2})$/);if(iso)return`${iso[1]}-${iso[2].padStart(2,'0')}-${iso[3].padStart(2,'0')}`;const numeric=value.match(/^(\d{1,2})[./-](\d{1,2})[./-](\d{4})$/);if(numeric)return`${numeric[3]}-${numeric[2].padStart(2,'0')}-${numeric[1].padStart(2,'0')}`;const frenchMonths:Record<string,string>={janvier:'01',fevrier:'02','février':'02',mars:'03',avril:'04',mai:'05',juin:'06',juillet:'07',aout:'08','août':'08',septembre:'09',octobre:'10',novembre:'11',decembre:'12','décembre':'12'};const french=value.toLocaleLowerCase('fr-FR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').match(/^(\d{1,2})\s+([a-z]+)\s+(\d{4})$/);if(french){const month=frenchMonths[french[2]];if(month)return`${french[3]}-${month}-${french[1].padStart(2,'0')}`;}return value;}
  protected dryRun():void{this.attempted.set(true);if(!this.importValid())return;const rows=this.rows();if(!rows.length){this.error.set(this.fr()?'Aucune ligne exploitable.':'No usable row.');return;}this.working.set(true);this.error.set(null);this.api.familyImportDryRun(rows,this.fileName()||'modele-eleves.csv').subscribe({next:result=>{this.working.set(false);this.result.set(result);},error:e=>{this.working.set(false);this.error.set(e.error?.message||'Import impossible');}});}
  protected importValid():boolean{return!!this.classId&&!!this.relationship.trim()&&!!this.text.trim();}
  protected commit():void{const id=this.result()?.jobId;if(!id)return;this.working.set(true);this.error.set(null);this.api.familyImportCommit(id).subscribe({next:result=>{this.working.set(false);this.result.set(result);},error:e=>{this.working.set(false);this.error.set(e.error?.message||'Import impossible');}});}
}
