import {ChangeDetectionStrategy,ChangeDetectorRef,Component,inject,signal} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {Router,RouterLink} from '@angular/router';
import {SetupApi,ClassView} from '../../core/setup.api';
import {I18nService} from '../../core/i18n.service';
import {CardComponent,IconComponent,PageHeaderComponent} from '../../core/ui';
import {GuardianInput,GuardianSearchView,StudentApi,StudentUpsert} from './students.api';

@Component({selector:'bbc-student-registration',standalone:true,changeDetection:ChangeDetectionStrategy.OnPush,imports:[FormsModule,RouterLink,CardComponent,IconComponent,PageHeaderComponent],template:`
<div class="fade-in max-w-5xl mx-auto space-y-5"><bbc-page-header [title]="fr()?'Inscrire un nouvel élève':'Register a new student'" [subtitle]="fr()?'Élève, classe et famille dans une seule opération':'Student, placement and family in one operation'"><a right routerLink="/students" class="btn-secondary"><bbc-icon name="chevronLeft" [s]="14"/> {{fr()?'Annuler':'Cancel'}}</a></bbc-page-header>
<bbc-card><div class="flex gap-2 mb-7">@for(label of labels();track $index){<div class="flex-1"><div class="h-1.5 rounded-full" [class]="$index<=step()?'bg-brand-600':'bg-slate-200'"></div><div class="text-[11px] mt-1" [class]="$index===step()?'font-bold text-brand-700':'text-mute'">{{$index+1}}. {{label}}</div></div>}</div>
@if(step()===0){<section class="space-y-4"><h2 class="text-lg font-bold">{{fr()?'Identité de l’élève':'Student identity'}}</h2><div class="grid md:grid-cols-2 gap-4"><label><span class="label">{{fr()?'Nom':'Last name'}} *</span><input class="input w-full" [(ngModel)]="student.lastName"/></label><label><span class="label">{{fr()?'Prénom':'First name'}} *</span><input class="input w-full" [(ngModel)]="student.firstName"/></label><label><span class="label">{{fr()?'Sexe':'Sex'}}</span><select class="input w-full" [(ngModel)]="student.sex"><option value="M">{{fr()?'Masculin':'Male'}}</option><option value="F">{{fr()?'Féminin':'Female'}}</option></select></label><label><span class="label">{{fr()?'Date de naissance':'Date of birth'}}</span><input type="date" class="input w-full" [(ngModel)]="student.dob"/></label><label><span class="label">NIU</span><input class="input w-full" [(ngModel)]="student.niu"/></label><label><span class="label">{{fr()?'Lieu de naissance':'Birthplace'}}</span><input class="input w-full" [(ngModel)]="student.birthplace"/></label></div></section>}
@if(step()===1){<section class="space-y-4"><h2 class="text-lg font-bold">{{fr()?'Placement scolaire':'School placement'}}</h2><label class="block"><span class="label">{{fr()?'Classe actuelle':'Current class'}} *</span><select class="input w-full" [(ngModel)]="student.classId"><option [ngValue]="null">—</option>@for(c of classes();track c.id){<option [value]="c.id">{{c.name}} · {{c.subsystem}} · {{c.level}}</option>}</select></label><div class="p-3 rounded-xl bg-blue-50 text-blue-800 text-sm">{{fr()?'L’inscription est automatiquement liée à la session académique courante.':'Enrollment is automatically linked to the current academic session.'}}</div></section>}
@if(step()===2){<section class="space-y-4"><div class="flex justify-between"><h2 class="text-lg font-bold">{{fr()?'Parents et tuteurs':'Parents and guardians'}}</h2><button class="btn-secondary" (click)="addGuardian()"><bbc-icon name="plus" [s]="14"/> {{fr()?'Ajouter':'Add'}}</button></div>
@for(g of guardians;track $index){<div class="p-4 border rounded-xl space-y-3"><div class="flex justify-between"><b>{{fr()?'Adulte':'Adult'}} {{$index+1}}</b>@if(guardians.length>1){<button class="text-rose-600" (click)="guardians.splice($index,1)">×</button>}</div><div class="flex gap-2"><input class="input flex-1" [(ngModel)]="queries[$index]" [placeholder]="fr()?'Rechercher un parent existant':'Search existing guardian'"/><button class="btn-secondary" (click)="search($index)">{{fr()?'Rechercher':'Search'}}</button></div>@for(r of searchResults[$index]||[];track r.id){<button class="w-full text-left p-2 bg-slate-50 rounded-lg" (click)="useExisting($index,r)"><b>{{r.displayName}}</b> · {{r.maskedEmail}} · {{r.linkedChildren}} {{fr()?'enfant(s)':'child(ren)'}}</button>}
<div class="grid md:grid-cols-2 gap-3"><input class="input" [(ngModel)]="g.displayName" [placeholder]="fr()?'Nom complet *':'Full name *'"/><input class="input" [(ngModel)]="g.relationshipType" [placeholder]="fr()?'Mère, père, tuteur…':'Mother, father, guardian…'"/><input class="input" type="email" [(ngModel)]="g.email" placeholder="E-mail"/><input class="input" [(ngModel)]="g.phone" [placeholder]="fr()?'Téléphone':'Phone'"/></div></div>}</section>}
@if(step()===3){<section class="space-y-4"><h2 class="text-lg font-bold">{{fr()?'Accès au portail parent':'Parent portal access'}}</h2>@for(g of guardians;track $index){<div class="p-4 border rounded-xl"><b>{{g.displayName||('Parent '+($index+1))}}</b><select class="input w-full mt-2" [(ngModel)]="g.accessMode"><option value="SEND_INVITE">{{fr()?'Envoyer une invitation par e-mail':'Send email invitation'}}</option><option value="CREATE_ACCOUNT">{{fr()?'Créer maintenant avec mot de passe':'Create now with password'}}</option><option value="NO_PORTAL">{{fr()?'Aucun accès portail':'No portal access'}}</option></select>@if(g.accessMode==='CREATE_ACCOUNT'){<input type="password" class="input w-full mt-2" [(ngModel)]="g.initialPassword" [placeholder]="fr()?'8 caractères, une lettre et un chiffre':'8 characters, one letter and one number'"/>}</div>}</section>}
@if(step()===4){<section class="space-y-4"><h2 class="text-lg font-bold">{{fr()?'Vérification':'Review'}}</h2><div class="grid md:grid-cols-2 gap-4"><div class="p-4 bg-slate-50 rounded-xl"><div class="meta">{{fr()?'Élève':'Student'}}</div><b>{{student.lastName}} {{student.firstName}}</b><div>{{className()}}</div></div><div class="p-4 bg-slate-50 rounded-xl"><div class="meta">{{fr()?'Famille':'Family'}}</div>@for(g of guardians;track $index){<div><b>{{g.displayName}}</b> · {{g.relationshipType}} · {{g.accessMode}}</div>}</div></div><div class="p-3 bg-emerald-50 text-emerald-800 rounded-xl text-sm">{{fr()?'La validation crée l’élève, son inscription et tous les liens familiaux dans une seule transaction. En cas d’erreur, rien n’est conservé.':'Confirmation creates the student, enrollment and all family links in one transaction. On error, nothing is retained.'}}</div></section>}
@if(step()===5&&result()){<section class="text-center py-8"><div class="w-14 h-14 mx-auto rounded-full bg-emerald-100 text-emerald-700 flex items-center justify-center"><bbc-icon name="check" [s]="26"/></div><h2 class="text-xl font-bold mt-3">{{fr()?'Inscription terminée':'Registration complete'}}</h2><div class="font-mono mt-2">{{result()!.student.matricule}}</div><p class="text-sm text-mute mt-2">{{fr()?'Les invitations demandées ont été préparées. Aucun mot de passe n’est affiché ou conservé en clair.':'Requested invitations were prepared. No password is displayed or stored in plaintext.'}}</p><button class="btn-primary mt-5" (click)="router.navigate(['/students',result()!.student.id])">{{fr()?'Ouvrir la fiche élève':'Open student profile'}}</button></section>}
@if(error()){<div class="mt-4 p-3 bg-rose-50 text-rose-700 rounded-xl">{{error()}}</div>}
@if(step()<5){<div class="flex justify-between mt-8 pt-5 border-t"><button class="btn-secondary" [disabled]="step()===0" (click)="step.set(step()-1)">{{fr()?'Précédent':'Previous'}}</button>@if(step()<4){<button class="btn-primary" [disabled]="!validStep()" (click)="step.set(step()+1)">{{fr()?'Continuer':'Continue'}}</button>}@else{<button class="btn-primary" [disabled]="saving()" (click)="submit()">{{saving()?(fr()?'Création…':'Creating…'):(fr()?'Confirmer l’inscription':'Confirm registration')}}</button>}</div>}
</bbc-card></div>`})
export class StudentRegistrationComponent{
  private api=inject(StudentApi);private setup=inject(SetupApi);private cdr=inject(ChangeDetectorRef);protected router=inject(Router);private i18n=inject(I18nService);protected fr=()=>this.i18n.lang()==='fr';protected step=signal(0);protected classes=signal<ClassView[]>([]);protected saving=signal(false);protected error=signal<string|null>(null);protected result=signal<any|null>(null);protected labels=()=>this.fr()?['Élève','Classe','Famille','Accès','Vérifier']:['Student','Class','Family','Access','Review'];
  protected student:StudentUpsert={firstName:'',lastName:'',niu:'',sex:'M',dob:null,birthplace:'',repeats:false,classId:null,parentName:'',parentPhone:''};protected guardians:GuardianInput[]=[this.blankGuardian()];protected queries:string[]=[''];protected searchResults:GuardianSearchView[][]=[[]];
  constructor(){this.setup.listClasses().subscribe(c=>this.classes.set(c));}
  protected addGuardian(){this.guardians.push(this.blankGuardian());this.queries.push('');this.searchResults.push([]);}
  protected search(i:number){const q=this.queries[i]?.trim();if(!q||q.length<3)return;this.api.searchGuardians(q).subscribe({next:r=>{this.searchResults[i]=r;this.cdr.markForCheck()},error:e=>this.error.set(e.error?.message)});}
  protected useExisting(i:number,r:GuardianSearchView){this.guardians[i].guardianId=r.id;this.guardians[i].displayName=r.displayName;this.guardians[i].accessMode='NO_PORTAL';this.searchResults[i]=[];this.cdr.markForCheck();}
  protected validStep(){switch(this.step()){case 0:return !!this.student.firstName.trim()&&!!this.student.lastName.trim();case 1:return !!this.student.classId;case 2:return this.guardians.every(g=>!!g.displayName.trim()&&!!g.relationshipType.trim());case 3:return this.guardians.every(g=>g.accessMode==='NO_PORTAL'||!!g.email?.trim())&&this.guardians.every(g=>g.accessMode!=='CREATE_ACCOUNT'||!!g.initialPassword&&g.initialPassword.length>=8);default:return true;}}
  protected className(){return this.classes().find(c=>c.id===this.student.classId)?.name||'—';}
  protected submit(){this.saving.set(true);this.error.set(null);this.api.register({student:this.student,guardians:this.guardians}).subscribe({next:r=>{this.saving.set(false);this.result.set(r);this.step.set(5)},error:e=>{this.saving.set(false);this.error.set(e.error?.message||'Inscription impossible')}});}
  private blankGuardian():GuardianInput{return{displayName:'',email:'',phone:'',relationshipType:'GUARDIAN',accessMode:'SEND_INVITE',legalGuardian:true,pickupAuthorized:true,receivesAcademic:true,receivesAttendance:true,portalAccess:true};}
}
