package com.bbc.sms.platform.security;

import java.util.Map;

/** Stable action codes used by method security and the Angular action catalogue. */
public final class PermissionActions {
    private PermissionActions() {}

    public record Requirement(String module, String level) {}

    public static final Map<String, Requirement> CATALOG = Map.ofEntries(
            Map.entry("SESSION_VIEW", new Requirement("settings", "read")),
            Map.entry("SESSION_MANAGE", new Requirement("settings", "write")),
            Map.entry("ACADEMIC_WINDOW_OVERRIDE", new Requirement("settings", "write")),
            Map.entry("ENROLLMENT_VIEW", new Requirement("students", "read")),
            Map.entry("ENROLLMENT_MANAGE", new Requirement("students", "write")),
            Map.entry("CALENDAR_VIEW", new Requirement("settings", "read")),
            Map.entry("CALENDAR_MANAGE", new Requirement("settings", "write")),
            Map.entry("AUDIT_VIEW", new Requirement("settings", "read")),
            Map.entry("DOCUMENT_VIEW", new Requirement("documents", "read")),
            Map.entry("DOCUMENT_DESIGN_PUBLISH", new Requirement("settings", "write")),
            Map.entry("DOCUMENT_GENERATE", new Requirement("documents", "write")),
            Map.entry("DOCUMENT_REVOKE", new Requirement("documents", "write")),
            Map.entry("GUARDIAN_LINK", new Requirement("students", "write")),
            Map.entry("ATTENDANCE_MARK", new Requirement("presence", "write")),
            Map.entry("ATTENDANCE_FINALIZE", new Requirement("presence", "write")),
            Map.entry("ATTENDANCE_REOPEN", new Requirement("presence", "write")),
            Map.entry("GRADE_SUBMIT", new Requirement("academic", "write")),
            // Academic data-scope management remains separate from the module
            // gate.  AcademicAccessPolicyService still resolves the requested
            // session/class/subject before allowing an operation.
            Map.entry("ACADEMIC_CLASS_RESULTS_VIEW", new Requirement("academic", "read")),
            Map.entry("ACADEMIC_REPORT_CARD_VIEW", new Requirement("academic", "read")),
            Map.entry("ACADEMIC_SUBJECT_GRADE_EDIT", new Requirement("academic", "write")),
            Map.entry("ACADEMIC_ASSESSMENT_MANAGE", new Requirement("academic", "write")),
            Map.entry("ACADEMIC_GRADE_PACKET_REVIEW", new Requirement("academic", "write")),
            Map.entry("ACADEMIC_REPORT_CARD_VALIDATE", new Requirement("academic", "write")),
            Map.entry("ACADEMIC_REPORT_CARD_PUBLISH", new Requirement("academic", "write")),
            Map.entry("ACADEMIC_ACCESS_DELEGATE", new Requirement("settings", "write")),
            Map.entry("ACADEMIC_ACCESS_AUDIT_VIEW", new Requirement("settings", "read")),
            Map.entry("ACADEMIC_COUNCIL_INPUT_EDIT", new Requirement("academic", "write")),
            Map.entry("BULLETIN_VALIDATE", new Requirement("academic", "write")),
            Map.entry("BULLETIN_PUBLISH", new Requirement("academic", "write")),
            Map.entry("PROMOTION_RECOMMEND", new Requirement("academic", "write")),
            Map.entry("PROMOTION_OVERRIDE", new Requirement("academic", "write")),
            Map.entry("PROMOTION_COMMIT", new Requirement("academic", "write")),
            Map.entry("PROGRESSION_VIEW", new Requirement("journey", "read")),
            Map.entry("PROGRESSION_CONFIGURE", new Requirement("journey", "write")),
            Map.entry("PROMOTION_REVIEW", new Requirement("journey", "write")),
            Map.entry("PROMOTION_CONFIGURE", new Requirement("journey", "write")),
            Map.entry("PROMOTION_CORRECT", new Requirement("journey", "write")),
            Map.entry("FEE_CONFIGURE", new Requirement("finance", "write")),
            Map.entry("FINANCE_OVERVIEW_VIEW", new Requirement("finance", "read")),
            Map.entry("FEE_TYPE_MANAGE", new Requirement("finance", "write")),
            Map.entry("FEE_PLAN_DRAFT", new Requirement("finance", "write")),
            Map.entry("FEE_PLAN_ACTIVATE", new Requirement("finance", "write")),
            Map.entry("CHARGE_PREVIEW", new Requirement("finance", "read")),
            Map.entry("CHARGE_GENERATE", new Requirement("finance", "write")),
            Map.entry("CHARGE_ADJUST", new Requirement("finance", "write")),
            Map.entry("FEE_WAIVE_REQUEST", new Requirement("finance", "write")),
            Map.entry("FEE_WAIVE_APPROVE", new Requirement("finance", "write")),
            Map.entry("PAYMENT_COLLECT", new Requirement("finance", "write")),
            Map.entry("PAYMENT_VIEW", new Requirement("finance", "read")),
            Map.entry("PAYMENT_REVERSE", new Requirement("finance", "write")),
            Map.entry("REFUND_REQUEST", new Requirement("finance", "write")),
            Map.entry("REFUND_APPROVE", new Requirement("finance", "write")),
            Map.entry("CASHIER_SESSION_OPEN", new Requirement("finance", "write")),
            Map.entry("CASHIER_SESSION_CLOSE", new Requirement("finance", "write")),
            Map.entry("CASHIER_SESSION_APPROVE", new Requirement("finance", "write")),
            Map.entry("PROVIDER_CALLBACK_REVIEW", new Requirement("finance", "write")),
            Map.entry("FINANCE_DOCUMENT_GENERATE", new Requirement("finance", "write")),
            Map.entry("FINANCE_DOCUMENT_VOID", new Requirement("finance", "write")),
            Map.entry("FINANCE_DOCUMENT_VIEW", new Requirement("finance", "read")),
            Map.entry("FINANCE_DOCUMENT_SUPERSEDE", new Requirement("finance", "write")),
            Map.entry("FINANCE_DOCUMENT_BATCH", new Requirement("finance", "write")),
            Map.entry("ACCOUNT_MANAGE", new Requirement("finance", "write")),
            Map.entry("POSTING_RULE_MANAGE", new Requirement("finance", "write")),
            Map.entry("LEDGER_POST", new Requirement("finance", "write")),
            Map.entry("LEDGER_REVERSE", new Requirement("finance", "write")),
            Map.entry("LEDGER_CLOSE", new Requirement("finance", "write")),
            Map.entry("LEDGER_REOPEN", new Requirement("finance", "write")),
            Map.entry("PAYROLL_CALCULATE", new Requirement("hr", "write")),
            Map.entry("PAYROLL_VIEW", new Requirement("hr", "read")),
            Map.entry("PAYROLL_PERIOD_MANAGE", new Requirement("hr", "write")),
            Map.entry("PAYROLL_COMPONENT_MANAGE", new Requirement("hr", "write")),
            Map.entry("PAYROLL_ADJUST", new Requirement("hr", "write")),
            Map.entry("PAYROLL_REVIEW", new Requirement("hr", "write")),
            Map.entry("PAYROLL_APPROVE", new Requirement("hr", "write")),
            Map.entry("PAYROLL_PAY", new Requirement("hr", "write")),
            Map.entry("PAYROLL_VOID", new Requirement("hr", "write")),
            Map.entry("PAYSLIP_VIEW_ALL", new Requirement("hr", "read")),
            Map.entry("PAYSLIP_REGENERATE", new Requirement("hr", "write")),
            Map.entry("FINANCE_REPORT_VIEW", new Requirement("finance", "read")),
            Map.entry("FINANCE_EXPORT", new Requirement("finance", "read")),
            Map.entry("TIMETABLE_DRAFT", new Requirement("timetable", "write")),
            Map.entry("TIMETABLE_PUBLISH", new Requirement("timetable", "write")),
            Map.entry("TIMETABLE_OVERRIDE", new Requirement("timetable", "write")),
            Map.entry("HEALTH_CONFIDENTIAL_VIEW", new Requirement("health", "write"))
    );
}
